(library
 (name test_integration)
 (inline_tests
  (deps
   ../../examples/elevator/scenarios/up_down.sexp
   ../../examples/matching_engine/scenarios/basic.sexp))
 (libraries
  ananke.runtime
  ananke.replay
  ananke.scenario
  ananke.io
  ananke.elevator
  ananke.matching_engine
  base)
 (preprocess
  (pps ppx_jane ppx_inline_test)))
